insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Century', 'HONDA', 1993, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('E150', 'CHEVROLET', 2009, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Discovery', 'HONDA', 2001, 'VERMELHO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Endeavor', 'CHEVROLET', 2007, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Montero Sport', 'FIAT', 2001, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Esperante', 'HONDA', 2007, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Express', 'HONDA', 2006, 'VERDE', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Accord', 'FIAT', 1996, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Elantra', 'HONDA', 2013, 'VERDE', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('2500 Club Coupe', 'CHEVROLET', 1996, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Escalade', 'VOLKSWAGEN', 1999, 'VERDE', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('GS', 'CHEVROLET', 2000, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Sentra', 'FORD', 2012, 'VERDE', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S-Class', 'HONDA', 2010, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Tahoe', 'VOLKSWAGEN', 1997, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Jetta', 'HONDA', 2002, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('9-5', 'FORD', 2008, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Continental Flying Spur', 'FIAT', 2008, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Sephia', 'FORD', 1994, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Celica', 'HONDA', 1993, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S-Class', 'VOLKSWAGEN', 2009, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S4', 'VOLKSWAGEN', 2010, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('FX', 'CHEVROLET', 2011, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Miata MX-5', 'VOLKSWAGEN', 2007, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Eldorado', 'HONDA', 2000, 'VERDE', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Regal', 'VOLKSWAGEN', 1990, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Galant', 'FIAT', 1997, 'BRANCO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Festiva', 'FORD', 1992, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('745', 'CHEVROLET', 2004, 'BRANCO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Grand Prix', 'HONDA', 1991, 'VERDE', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Grand Am', 'VOLKSWAGEN', 2004, 'VERMELHO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Frontier', 'CHEVROLET', 2002, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('M3', 'HONDA', 2012, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Equinox', 'FORD', 2010, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Spyder', 'HONDA', 2004, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Grand Prix', 'VOLKSWAGEN', 1991, 'VERDE', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Town Car', 'VOLKSWAGEN', 1997, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Aerostar', 'FIAT', 1987, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Aztek', 'HONDA', 2002, 'BRANCO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Avalon', 'VOLKSWAGEN', 2010, 'AZUL', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('B-Series', 'FORD', 1996, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S4', 'FORD', 1994, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Topaz', 'HONDA', 1991, 'VERMELHO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S60', 'VOLKSWAGEN', 2002, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('EXP', 'VOLKSWAGEN', 1986, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Prelude', 'FORD', 1984, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Protege', 'HONDA', 2003, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Accord', 'VOLKSWAGEN', 1985, 'VERDE', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S10 Blazer', 'HONDA', 1994, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Ram 1500', 'FIAT', 2001, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Wrangler', 'VOLKSWAGEN', 2012, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('XL7', 'VOLKSWAGEN', 2009, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Express 1500', 'VOLKSWAGEN', 2011, 'VERMELHO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('E-Class', 'FIAT', 1997, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Santa Fe', 'CHEVROLET', 2011, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Econoline E150', 'VOLKSWAGEN', 1998, 'AZUL', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Golf', 'FORD', 1989, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('E-Class', 'CHEVROLET', 2004, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Sonoma', 'HONDA', 2003, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Acadia', 'FIAT', 2008, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('E-Class', 'HONDA', 2012, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Grand Prix', 'FIAT', 1995, 'VERDE', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S-Series', 'FORD', 2002, 'VERMELHO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Sonata', 'HONDA', 2009, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('3 Series', 'CHEVROLET', 2009, 'BRANCO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('New Beetle', 'HONDA', 2002, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Express 3500', 'FIAT', 1999, 'BRANCO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Mariner', 'FORD', 2007, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Mustang', 'FORD', 1967, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('T100', 'VOLKSWAGEN', 1997, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Firebird', 'FIAT', 2000, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Grand Prix', 'VOLKSWAGEN', 1986, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('911', 'FIAT', 2007, 'BRANCO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Caravan', 'FORD', 1992, 'BRANCO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Corolla', 'HONDA', 1994, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Swift', 'FORD', 1989, 'BRANCO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('CX', 'HONDA', 1989, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Thunderbird', 'FIAT', 1983, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S90', 'FORD', 1997, 'VERMELHO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S40', 'FIAT', 2008, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Chariot', 'FIAT', 1995, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('S6', 'CHEVROLET', 2009, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Somerset', 'HONDA', 1985, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Monte Carlo', 'VOLKSWAGEN', 1997, 'PRETO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Grand Marquis', 'FORD', 1995, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('90', 'VOLKSWAGEN', 1991, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('G-Class', 'FIAT', 2002, 'AMARELO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Legacy', 'VOLKSWAGEN', 1991, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Versa', 'CHEVROLET', 2010, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('GTI', 'FIAT', 1987, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Mark LT', 'FORD', 2007, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('G6', 'CHEVROLET', 2006, 'AMARELO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('911', 'FORD', 1999, 'BRANCO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('FJ Cruiser', 'HONDA', 2010, 'AZUL', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Space', 'FORD', 1994, 'AZUL', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Town & Country', 'CHEVROLET', 1999, 'VERDE', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Trans Sport', 'FIAT', 1998, 'VERMELHO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Altima', 'VOLKSWAGEN', 2012, 'VERMELHO', '', false);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Golf', 'VOLKSWAGEN', 2004, 'PRETO', '', true);
insert into veiculo (veiculo, marca, ano, cor, descricao, vendido) values ('Skylark', 'VOLKSWAGEN', 1998, 'PRETO', '', false);